development:
  adapter: postgresql
  encoding: unicode
  database: amplifize_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: amplifize_production
  pool: 5
  username: postgres
  password:

