# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: amplifize_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: amplifize_com
  pool: 5
  username: amplifize.com
  password: b1gFi$hBiGp0Nd
  socket: /tmp/mysql.sock
